version: '3.9'

services:
  postgresql-service:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: ejercicio
    ports:
      - "5432:5432"  # Mapeo de puertos
    volumes:
      - postgresql-vol:/var/lib/postgresql/data
    networks:
      - net-exercise
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 30s

  sonarqube-service:
    image: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql-service:5432/ejercicio
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=admin
    ports:
      - 9000:9000
    volumes:
      - sonarqube-vol-data:/opt/sonarqube/data
      - sonarqube-vol-logs:/opt/sonarqube/logs
      - sonarqube-vol-extensions:/opt/sonarqube/extensions
    networks:
      - net-exercise
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 50s
    restart: always

volumes:
  postgresql-vol:
  sonarqube-vol-data:
  sonarqube-vol-logs:
  sonarqube-vol-extensions:

networks:
  net-exercise:
    driver: bridge