version: '3.8'

services:
  mysql-service:
    image: mysql:8.4
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: practica5
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    volumes:
      - mysql-vol:/var/lib/mysql
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 30s

  wordpress-service:
    image: wordpress:6
    container_name: wordpress-container
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: admin
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin1234
      WORDPRESS_DB_NAME: practica5
    volumes:
      - wordpress-vol:/var/www/html
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 50s
    restart: always
    depends_on:
      mysql-service:
        condition: service_healthy
volumes:
  mysql-vol:
  wordpress-vol:

networks:
  net-wp:
    driver: bridge
